### ISSUE TITLE
Malformed output of the marks command

### ISSUE THREAD

**Issue by HackerTheMonkey** [HackerTheMonkey/the-bookmarker#10]
The marks command seems to be experiencing issues under certain environments in which the output seems not to be picking up the right fields, an example is as below:

`hassanein.khafaji@LON02785:~/opt/BookmarkerScript (master) $ marks
 14:04  /Users/hassanein.khafaji/.marks/bin ->
 14:41  /Users/hassanein.khafaji/.marks/chef_repos ->
 01:30  /Users/hassanein.khafaji/.marks/conf ->
 17:34  /Users/hassanein.khafaji/.marks/dispatcher ->
 12:08  /Users/hassanein.khafaji/.marks/https ->
 12:08  /Users/hassanein.khafaji/.marks/httpsmaps ->
 15:00  /Users/hassanein.khafaji/.marks/m2 ->
 14:12  /Users/hassanein.khafaji/.marks/map.publish ->
 11:06  /Users/hassanein.khafaji/.marks/maps ->
 14:05  /Users/hassanein.khafaji/.marks/opt ->
 14:04  /Users/hassanein.khafaji/.marks/pro ->
 17:08  /Users/hassanein.khafaji/.marks/recipes ->
 11:07  /Users/hassanein.khafaji/.marks/runmodes ->
 12:41  /Users/hassanein.khafaji/.marks/src ->
 11:38  /Users/hassanein.khafaji/.marks/tests ->
 14:45  /Users/hassanein.khafaji/.marks/tmp ->
 14:40  /Users/hassanein.khafaji/.marks/vagrant_author ->
 14:40  /Users/hassanein.khafaji/.marks/vagrant_publish ->
 11:02  /Users/hassanein.khafaji/.marks/workspace ->`

**Comment by hasanein** [comment]
Fixed.
